baseURL: "https://peaceful-donut-e0553c.netlify.app"
languageCode: en-us
title: Cookie's Notes
theme: fuji

params:
  homeInfoParams:
    Title: "hello fren"
    Content: hi hello welcome

  cover:
    linkFullImages: true
  
  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  BookTheme: "dark"

  enableEmoji: true


      